### ISSUE TITLE
Provide build instructions and Open Source Dockerfiles for builds

### ISSUE THREAD

**Issue by elfisher** [opendistro-for-elasticsearch/community#11] opened 2019-03-11 18:54 UTC
Provide the Dockerfiles and instructions used for building Open Distro for Elasticsearch.

**Comment by TimoKramer** [comment] 2019-03-11 23:51
And a hint on where to find the sources to build it myself. Is it built from elastic-repo with a tag or release-hash?

**Comment by rkettelerij** [comment] 2019-03-12 08:43
This is pretty important. Since this is called an _open distro_ it's crucial - in my opinion - to provide _reproducible builds._ Otherwise users are looking a binaries that are essentially a blackbox. So apart from Dockerfiles you may want to consider providing build scripts, ES patches, etc, etc. Basically every artifact/step required to get from source to binary.

**Comment by dansou901** [comment] 2019-03-13 09:02
Can you also provide ready-to-use docker images for all the components?

**Comment by gabrielcalderon** [comment] 2019-03-14 04:02
@dansou901 The Docker images are here: [](https://hub.docker.com/search?q=opendistro&type=image)

**Comment by imranh2** [comment] 2019-03-15 13:09
Clearer build instructions would be great.

I've managed to build the alerting and security plugins (for both ES and Kibana).


If anyone stumbles upon this comment:

Security ES Plugin is built using Maven (compile,package,install). You need to do security-parent -> security-ssl -> security-advanced-modules -> security (use profile advanced as veracode doesn't spit out a valid ES plugin zip). zip is spat out into target/releases/ as opendistro_security-0.7.0.0.zip

Security Kibana Plugin is built using Maven (compile,package).  git clone kibana (v6.5.4) source into build_stage dir. zip is spat out into target/releases/

Alerting ES Plugin is built using gradle. Output zip is in alerting/build/distributions/ Funninly enough you also get a .deb

Alerting Kibana Plugin has clear build instructions, won't bother repeating them.

**Comment by nibin** [comment] 2019-03-19 21:22
Any update on when the docker files will be released ?

**Comment by markharding** [comment] 2019-03-21 16:15
The project is described as "100% open source distribution of Elasticsearch", yet it is not possible to see the code or changes (from OS ElasticSearch) that you are running from either of the two installation methods (Docker and RPM).

I have managed to open up the docker image a little bit and found `/usr/local/bin/docker-entrypoint.sh`, but I'm still unaware of what has actually changed in ElasticSearch itself. Is this project purely plugins? If that is the case, it is possible to just take a single component such as the security plugin and install that on and existing elasticsearch cluster?

```bash
#!/bin/bash
set -e

# Files created by OpenDistroForElasticsearch should always be group writable too
umask 0002

run_as_other_user_if_needed() {
    if [[ "$(id -u)" == "0" ]]; then
        # If running as root, drop to specified UID and run command
        exec chroot --userspec=1000 / "${@}"
    else
        # Either we are running in Openshift with random uid and are a member of the root group
        # or with a custom --user
        exec "${@}"
    fi
}

# Allow user specify custom CMD, maybe bin/elasticsearch itself
# for example to directly specify `-E` style parameters for elasticsearch on k8s
# or simply to run /bin/bash to check the image
if [[ "$1" != "eswrapper" ]]; then
    if [[ "$(id -u)" == "0" && $(basename "$1") == "elasticsearch" ]]; then
        # centos:7 chroot doesn't have the `--skip-chdir` option and
        # changes our CWD.
        # Rewrite CMD args to replace $1 with `elasticsearch` explicitly,
        # so that we are backwards compatible with the docs
        # from the previous Elasticsearch versions<6
        # and configuration option D:
        # https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html#_d_override_the_image_8217_s_default_ulink_url_https_docs_docker_com_engine_reference_run_cmd_default_command_or_options_cmd_ulink
        # Without this, user could specify `elasticsearch -E x.y=z` but
        # `bin/elasticsearch -E x.y=z` would not work.
        set -- "elasticsearch" "${@:2}"
        # Use chroot to switch to UID 1000
        exec chroot --userspec=1000 / "$@"
    else
        # User probably wants to run something else, like /bin/bash, with another uid forced (Openshift?)
        exec "$@"
    fi
fi

# Parse Docker env vars to customize Elasticsearch
#
# e.g. Setting the env var cluster.name=testcluster
#
# will cause Elasticsearch to be invoked with -Ecluster.name=testcluster
#
# see https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html#_setting_default_settings

declare -a es_opts

while IFS='=' read -r envvar_key envvar_value
do
    # Elasticsearch settings need to have at least two dot separated lowercase
    # words, e.g. `cluster.name`, except for `processors` which we handle
    # specially
    if [[ "$envvar_key" =~ ^[a-z0-9_]+\.[a-z0-9_]+ || "$envvar_key" == "processors" ]]; then
        if [[ ! -z $envvar_value ]]; then
          es_opt="-E${envvar_key}=${envvar_value}"
          es_opts+=("${es_opt}")
        fi
    fi
done < <(env)

# The virtual file /proc/self/cgroup should list the current cgroup
# membership. For each hierarchy, you can follow the cgroup path from
# this file to the cgroup filesystem (usually /sys/fs/cgroup/) and
# introspect the statistics for the cgroup for the given
# hierarchy. Alas, Docker breaks this by mounting the container
# statistics at the root while leaving the cgroup paths as the actual
# paths. Therefore, Elasticsearch provides a mechanism to override
# reading the cgroup path from /proc/self/cgroup and instead uses the
# cgroup path defined the JVM system property
# es.cgroups.hierarchy.override. Therefore, we set this value here so
# that cgroup statistics are available for the container this process
# will run in.
export ES_JAVA_OPTS="-Des.cgroups.hierarchy.override=/ $ES_JAVA_OPTS"

if [[ "$(id -u)" == "0" ]]; then
    # If requested and running as root, mutate the ownership of bind-mounts
    if [[ -n "$TAKE_FILE_OWNERSHIP" ]]; then
        chown -R 1000:0 /usr/share/elasticsearch/{data,logs}
    fi
fi

CLK_TCK=`/usr/bin/getconf CLK_TCK`
ES_JAVA_OPTS="-Djava.security.policy=file:///usr/share/elasticsearch/plugins/opendistro_performance_analyzer/pa_config/es_security.policy -Dclk.tck=$CLK_TCK -Djdk.attach.allowAttachSelf=true $ES_JAVA_OPTS"

# Install Demo certifactes for Security Plugin and update the elasticsearch.yml
# file to use those certificates.
/usr/share/elasticsearch/plugins/opendistro_security/tools/install_demo_configuration.sh -y -i -s
/usr/bin/supervisord -c /usr/share/elasticsearch/plugins/opendistro_performance_analyzer/pa_config/supervisord.conf
run_as_other_user_if_needed /usr/share/elasticsearch/bin/elasticsearch "${es_opts[@]}
```

**Comment by CarlMeadows** [comment] 2019-03-21 16:38
Agree @markharding We are working on opening these elements up so that we can be transparent and can accept community contributions to the build process. We are also working on getting all artifacts available in Maven Central so the community can build all of the plugins separately if they choose too. I think both issues have been tagged into the backlog and should be coming soon.

**Comment by TimoKramer** [comment] 2019-03-21 19:58
@markharding when you open up the rpm with rpm2cpio you will see, that it is pure elasticsearch-oss 6.5 and the plugins.

**Comment by Jon-AtAWS** [comment] 2019-04-02 20:00
For those interested in building the plugins themselves, I have written a blog post describing [how to build and use the SQL](https://aws-blogs-prod.amazon.com/opensource/build-run-sql-plugin-open-distro-elasticsearch-oss/) plugin with Elasticsearch OSS.

I'm working on posts with instructions for the other plugins as well. Stay tuned!

Jon

**Comment by rkettelerij** [comment] 2019-04-04 08:09
@Jon-AtAWS the above link doesn't work, correct link: https://aws.amazon.com/blogs/opensource/build-run-sql-plugin-open-distro-elasticsearch-oss/

**Comment by Jon-AtAWS** [comment] 2019-04-05 20:21
Thanks so much for the correction!

**Comment by pombredanne** [comment] 2019-04-08 11:57
@CarlMeadows you wrote 18 days ago: 

> Agree @markharding We are working on opening these elements up so that we can be transparent and can accept community contributions to the build process. 

Would you have any update on this? A build script sounds rather essential to me and I was surprised that I could not find these and they did not come up first with your initial release. That and being able to obtain the corresponding source are pretty basic necessary but not even sufficient to make this "open".

**Comment by mysticaltech** [comment] 2019-04-09 09:28
Having a Kubernetes helm chat would be great too!

**Comment by halkazzar** [comment] 2019-04-09 21:49
> Having a Kubernetes helm chat would be great too!

We are tracking Helm Chart request here:  #13

**Comment by halkazzar** [comment] 2019-04-09 21:49
> @CarlMeadows you wrote 18 days ago:
> 
> > Agree @markharding We are working on opening these elements up so that we can be transparent and can accept community contributions to the build process.
> 
> Would you have any update on this? A build script sounds rather essential to me and I was surprised that I could not find these and they did not come up first with your initial release. That and being able to obtain the corresponding source are pretty basic necessary but not even sufficient to make this "open".

the team took this issue into a sprint this week. Stay tuned!

**Comment by unixtastic** [comment] 2019-04-26 22:17
I suggest this ticket should be split into "Provide build instructions" and "Provide Dockerfiles". These are two totally separate things. Being able to automatically build this with a CI tool like jenkins and produce a jar is essential. Providing support to bundle that jar with docker, rpm, deb, or anything else is very useful but not essential.

**Comment by alolita** [comment] 2019-05-01 17:28
@unixtastic agreed. Can you please open 2 issues :-) else I can.

**Comment by pombredanne** [comment] 2019-05-01 17:37
FWIW, the thing I care for is to get the sources.

**Comment by fredbcode** [comment] 2019-05-15 08:29
Yes the source is the priority, what is really changed in ElasticSearch itself ?

**Comment by CarlMeadows** [comment] 2019-05-16 16:49
HI all. Happy to say we have published the build scripts - please take a look and open any issues for them in their repo: https://github.com/opendistro-for-elasticsearch/opendistro-build

**Closed by CarlMeadows** 2019-05-16 16:49 UTC

**Comment by apigban** [comment] 2019-11-05 13:32
I can't seem to find the docker files, were they provided with the build guide?

**Comment by captn3m0** [comment] 2019-11-05 14:53
It is templated: https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/elasticsearch/docker/templates/Dockerfile.j2

You need to build the dockerfile before you can build the docker image.
