### ISSUE TITLE
Email alert no sending

### ISSUE THREAD

**Issue by Andrew302** [opendistro-for-elasticsearch/community#41] opened 2019-04-05 09:12 UTC
Hi

I try configurate Alerting Open Distro.  the problem is when try configurate destinations  Amazon SNS and the emails not sending. The problem is i need specific IAM role ARN and a specific SNS ARN Role?

thanks

**Comment by elfisher** [comment] 2019-04-05 17:42
Moving this to the alerting repo. new issue here: https://github.com/opendistro-for-elasticsearch/alerting/issues/24

**Closed by elfisher** 2019-04-05 17:42 UTC

**Comment by bramu-rythmos** [comment] 2019-07-29 09:13
We are able to get the alerts in sei-perf on messages ready count. But the problem is we are getting only one alert out of 25 hits or queues. It is beacause tx.results[0].hits.hits[1]._source.rabbitmq.queue.messages.ready.count>1000, in these condition we are calling only first hit condition. If we can find out how to make it iterative like hits[i>0], we will get the all the values. But it is not accepting the condition. Will work on this and update. 
![image](https://user-images.githubusercontent.com/49273995/62036101-c079ba00-b20e-11e9-9532-cfd2d21d7142.png)

![image](https://user-images.githubusercontent.com/49273995/62036116-c8d1f500-b20e-11e9-962a-4964833af221.png)
